version: '{build}'
shallow_clone: true

branches:
  except:
    - /issue\d+/
environment:
  matrix:
    - perl_type: cygwin

install:
  - 'call .appveyor.cmd perl_setup'
  - '%perl% -V'
  - '%cpanm% --installdeps -n --with-develop --with-recommends .'

build: off

build_script:
  - '%perl% Makefile.PL'
  - 'make test'
test_script:
  - 'make test'
