language: perl
perl:
  - 5.8.1
  - 5.8.3
  - 5.8.6
  - 5.8.7
  - 5.8.8
  - 5.8.9
  - 5.10.1
  - 5.12.3
  - 5.14.4
  - 5.16.3
  - 5.18.4
  - 5.20.3
  - 5.22.1
before_install:
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
